version: "3.8"

services:
  db:
    image: postgres:15
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  calculator:
    image: macdoncml.azurecr.io/fastmcp-calculator:latest
    platform: linux/amd64
    expose:
      - "8001"
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/app/src           
    env_file: .env
    depends_on:
      - db
      - calculator
    environment:
      DATABASE_URL: postgresql://postgres:secretpassword@db:5432/postgres
      MCP_BASE_URL: http://calculator:8001
      PYTHONPATH: /app/src       
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    ports:
      - "8000:80"
    networks:
      - backend

  dev:
    # helper container just for shell / kubectl / helm / az
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/root/.kube
      - ~/.azure:/root/.azure
    working_dir: /workspace
    environment:
      KUBECONFIG: /root/.kube/config
      PYTHONPATH: /workspace/src
    command: sleep infinity
    stdin_open: true
    tty: true
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
