apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-upgrade
  namespace: rag
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        # ensure Alembic sees your migrations and config:
        workingDir: /app                    # where alembic.ini lives
        env:
          - name: PYTHONPATH
            value: /app/src                # where your app package lives
        envFrom:
          - secretRef:
              name: rag-api-secret
        command:
          - sh
          - -c
          - |
            echo "➤ Running Alembic migrations…" &&
            alembic upgrade head
