# helm/rag-api/templates/alembic-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-upgrade
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          workingDir: /app
          env:
            - name: PYTHONPATH
              value: /app/src
          envFrom:
            - secretRef:
                name: rag-api-secret
          command:
            - sh
            - -c
            - |
              echo "➤ Running Alembic migrations…" &&
              alembic upgrade head
