apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            # All sensitive values from secret
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-api-secret
                  key: OPENAI_API_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rag-api-secret
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-api-secret
                  key: SECRET_KEY
            - name: USER_SALT
              valueFrom:
                secretKeyRef:
                  name: rag-api-secret
                  key: USER_SALT

            # Non-secret values from values.yaml
            - name: LLM_PROVIDER
              value: {{ .Values.env.LLM_PROVIDER | quote }}
            - name: EMBEDDING_PROVIDER
              value: {{ .Values.env.EMBEDDING_PROVIDER | quote }}
            - name: USER_REPOSITORY
              value: {{ .Values.env.USER_REPOSITORY | quote }}
            - name: PROMPT_PATH
              value: {{ .Values.env.PROMPT_PATH | quote }}
            - name: TAVILY_BASE_URL
              value: {{ .Values.env.TAVILY_BASE_URL | quote }}