apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
spec:
  tls:
    - hosts:
        - api.macdonml.com
      secretName: "rag-api-tls"
  rules:
    - host: api.macdonml.com
      http:
        paths:
          - path: /token
            pathType: Prefix
            backend:
              service:
                name: rag-api
                port:
                  number: {{ .Values.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rag-api
                port:
                  number: {{ .Values.service.port }}
